#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${SPLITVPN_ENV:-/etc/splitvpn/splitvpn.env}"
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="${BASE_DIR}/templates/splitvpn.nft.tmpl"

if [[ ! -r "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

required_vars=(
  WG_IN_IF WG_OUT_IF WAN_IF DNS_LISTEN_ADDRESS DNS_UPSTREAMS
  RU_MARK WG_MARK NFT_CONF DNSMASQ_CONF GENERATED_DIR
)

for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "Required variable is empty: $var" >&2
    exit 1
  fi
done

mkdir -p "$GENERATED_DIR" "$(dirname "$DNSMASQ_CONF")"

resolve_dns_backend() {
  local backend="${DNS_SET_BACKEND:-auto}"

  case "$backend" in
    nftset|ipset)
      printf '%s\n' "$backend"
      return
      ;;
    auto)
      if command -v dnsmasq >/dev/null 2>&1 && dnsmasq --version 2>/dev/null | grep -q ' no-nftset '; then
        printf '%s\n' "ipset"
      else
        printf '%s\n' "nftset"
      fi
      return
      ;;
    *)
      echo "Invalid DNS_SET_BACKEND: $backend. Use auto, nftset, or ipset." >&2
      exit 1
      ;;
  esac
}

DNS_BACKEND="$(resolve_dns_backend)"
IPSET_DOMAIN_SET="${IPSET_DOMAIN_SET:-splitvpn_ru_domain_v4}"
IPSET_FORCE_RU_SET="${IPSET_FORCE_RU_SET:-splitvpn_force_ru_v4}"
IPSET_FORCE_FI_SET="${IPSET_FORCE_FI_SET:-splitvpn_force_fi_v4}"
FORCE_RU_FILE="${FORCE_RU_FILE:-${ETC_DIR:-/etc/splitvpn}/force-ru.txt}"
FORCE_FI_FILE="${FORCE_FI_FILE:-${ETC_DIR:-/etc/splitvpn}/force-fi.txt}"
printf '%s\n' "$DNS_BACKEND" > "$GENERATED_DIR/dns-set-backend"

sed_escape() {
  printf '%s' "$1" | sed -e 's/[\/&]/\\&/g'
}

DNS_REDIRECT_RULES=""
if [[ "${FORCE_CLIENT_DNS:-1}" == "1" ]]; then
  DNS_REDIRECT_RULES='    iifname "__WG_IN_IF__" udp dport 53 redirect to :53
    iifname "__WG_IN_IF__" tcp dport 53 redirect to :53'
fi

is_ipv4_or_cidr() {
  [[ "$1" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?$ ]]
}

normalize_domain() {
  local item="$1"
  if [[ "$item" == \*.* ]]; then
    item="${item#*.}"
  fi
  item="${item%.}"
  printf '%s\n' "$item"
}

read_manual_domains() {
  local file="$1"
  local raw item

  [[ -r "$file" ]] || return 0
  while IFS= read -r raw || [[ -n "$raw" ]]; do
    item="${raw%%#*}"
    item="$(printf '%s' "$item" | tr -d '\r' | xargs)"
    [[ -n "$item" ]] || continue
    is_ipv4_or_cidr "$item" && continue
    normalize_domain "$item"
  done < "$file" | sort -u
}

emit_dns_set_rule() {
  local domain="$1"
  local target="$2"

  if [[ "$DNS_BACKEND" == "nftset" ]]; then
    echo "nftset=/$domain/4#inet#splitvpn#$target"
  else
    echo "ipset=/$domain/$target"
  fi
}

sed \
  -e "s/__WG_IN_IF__/$(sed_escape "$WG_IN_IF")/g" \
  -e "s/__WG_OUT_IF__/$(sed_escape "$WG_OUT_IF")/g" \
  -e "s/__WAN_IF__/$(sed_escape "$WAN_IF")/g" \
  -e "s/__RU_MARK__/$(sed_escape "$RU_MARK")/g" \
  -e "s/__WG_MARK__/$(sed_escape "$WG_MARK")/g" \
  -e "s/__DNS_REDIRECT_RULES__/$(printf '%s' "$DNS_REDIRECT_RULES" | sed -e ':a' -e 'N' -e '$!ba' -e 's/[\/&]/\\&/g' -e 's/\n/\\n/g')/g" \
  "$TEMPLATE" > "$NFT_CONF"

{
  echo "# Generated by splitvpn render-configs.sh"
  echo "# DNS answers for .ru populate nft set inet splitvpn ru_domain_v4."
  echo "bind-interfaces"
  echo "interface=$WG_IN_IF"
  echo "listen-address=$DNS_LISTEN_ADDRESS"
  echo "no-resolv"
  echo "cache-size=10000"
  echo "domain-needed"
  echo "bogus-priv"
  for upstream in $DNS_UPSTREAMS; do
    echo "server=$upstream"
  done
  if [[ "$DNS_BACKEND" == "nftset" ]]; then
    echo "nftset=/ru/4#inet#splitvpn#ru_domain_v4"
  else
    echo "ipset=/ru/$IPSET_DOMAIN_SET"
  fi
  while IFS= read -r domain; do
    [[ -n "$domain" ]] || continue
    emit_dns_set_rule "$domain" "$([[ "$DNS_BACKEND" == "nftset" ]] && printf force_ru_v4 || printf '%s' "$IPSET_FORCE_RU_SET")"
  done < <(read_manual_domains "$FORCE_RU_FILE")
  while IFS= read -r domain; do
    [[ -n "$domain" ]] || continue
    emit_dns_set_rule "$domain" "$([[ "$DNS_BACKEND" == "nftset" ]] && printf force_fi_v4 || printf '%s' "$IPSET_FORCE_FI_SET")"
  done < <(read_manual_domains "$FORCE_FI_FILE")
} > "$DNSMASQ_CONF"

echo "Rendered:"
echo "  $NFT_CONF"
echo "  $DNSMASQ_CONF"
echo "  DNS set backend: $DNS_BACKEND"
